language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '12'
before_install:

before_script:
  - yarn
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/